packages:
  - "."
  - "packages/*"

strictDepBuilds: true

overrides:
  "@huggingface/transformers@4.2.0>sharp": 0.35.3
  "adm-zip@<0.6.0": ^0.6.0
  "html-to-text@10.0.0>deepmerge-ts": 8.0.1
  "onnxruntime-web@1.26.0-dev.20260416-b7804b056c>protobufjs": 7.6.5
  yaml: ^2.9.0

packageExtensions:
  "@huggingface/transformers@4.2.0":
    dependencies:
      onnxruntime-common: 1.24.3

allowBuilds:
  esbuild: true
  node-llama-cpp: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
